/**
 * @fileoverview Type definitions for check-in response data in Foodbank Check-In and Appointment System client application
 * 
 * This module defines TypeScript interfaces and types for handling check-in responses
 * from the backend API. It ensures type safety for client-side data handling and
 * provides clear contracts for API communication.
 * 
 * @version 1.0.0
 * @since 2025-10-20
 * @license Proprietary - see LICENSE file for details
 * 
 * @see {@link ../../features/checkin/services/checkInService.ts} Check-in service implementation
 */

export interface CheckInResponse {
  success: boolean;
  message?: string;
  data?: {
    checkInId: string;
    clientId: string;
    clientName: string;
    appointmentTime?: string;
    phoneNumber: string;
    pickUpTime?: string;
    pickUpDate?: string;
    nextAppointmentDate?: string;
    nextAppointmentTime?: string;
    nextAppointmentISO?: string;
    ticketNumber?: string;
    isAutoGenerated?: boolean;
    appointment?: {
      id?: string;
      date?: string;
      time?: string;
      status?: string;
      location?: string;
    };
    client?: {
      id?: string;
      firstName?: string;
      lastName?: string;
      fullName?: string;
      email?: string;
      phone?: string;
      dietary?: string;
    };
  };
  error?: string | { message: string; code?: string };
}

export interface CheckInFormData {
  firstName: string;
  lastName: string;
  phone: string;
  email?: string;
  appointmentId?: string;
  specialRequests?: string[];
}

export interface CheckInSession {
  firstName?: string;
  fullName?: string;
  phone?: string;
  lastName?: string;
  checkInId?: string;
  clientId?: string;
  clientName?: string;
  appointmentTime?: string;
  pickUpTime?: string;
  pickUpDate?: string;
  nextAppointmentDate?: string;
  nextAppointmentTime?: string;
  nextAppointmentISO?: string;
  ticketNumber?: string;
  isAutoGenerated?: boolean;
  appointment?: {
    id?: string;
    date?: string;
    time?: string;
    status?: string;
    location?: string;
  };
  client?: {
    id?: string;
    firstName?: string;
    lastName?: string;
    fullName?: string;
    email?: string;
    phone?: string;
    dietary?: string;
  };
}
