/**
 * @fileoverview Check-ins management page for Foodbank Check-In and Appointment System admin panel
 * 
 * This page provides comprehensive check-in management functionality
 * including viewing all check-ins, filtering, searching, and managing
 * client appointments and status updates.
 * 
 * @author Lindsey D. Stead
 * @version 1.0.0
 * @since 2025-10-20
 * @license Proprietary - see LICENSE file for details
 * 
 * @see {@link ../components/features/dashboard/CheckInDataGrid.tsx} Data grid component
 */

import React, { useState, useEffect } from 'react';
import {
  Box,
  VStack,
  HStack,
  Text,
  Input,
  Button,
  Badge,
  Card,
  CardHeader,
  CardBody,
  Avatar,
  Skeleton,
  SkeletonCircle,
  Tooltip,
  IconButton,
  useDisclosure,
  Modal,
  ModalOverlay,
  ModalContent,
  ModalHeader,
  ModalCloseButton,
  ModalBody,
  ModalFooter,
  Grid,
  Alert,
  AlertIcon,
  Center,
  Heading,
} from '@chakra-ui/react';
import { 
  FiSearch, 
  FiPrinter, 
  FiEye, 
  FiUsers, 
  FiClock, 
  FiPhone, 
  FiMail,
  FiRefreshCw,
  FiX,
  FiDownload
} from 'react-icons/fi';
import { formatDistanceToNow } from 'date-fns';
import { formatToVancouverTime, formatToVancouverTimeOnly } from '../utils/timeFormatter';
import { formatPhoneNumber } from '../common/utils/phoneFormatter';
import { getApiUrl } from '../common/apiConfig';

interface CheckInRecord {
  id: string;
  clientId: string;
  clientName: string;
  phoneNumber: string;
  checkInTime: string;
  appointmentTime?: string;
  status: 'Pending' | 'Shipped' | 'Collected' | 'Not Collected' | 'Rescheduled' | 'Cancelled';
  source: 'csv' | 'manual' | 'api';
  
  // Client data from CSV
  firstName?: string;
  lastName?: string;
  email?: string;
  dietaryConsiderations?: string;
  householdSize?: number;
  adults?: number;
  seniors?: number;
  children?: number;
  childrensAges?: string;
  childrenAges?: string;
  itemsProvided?: string;
  notes?: string;
  
  // Check-in completion data
  completionTime?: string;
  dietaryRestrictions?: string[];
  allergies?: string;
  unwantedFoods?: string;
  additionalInfo?: string;
  householdInfoChanged?: boolean;
  hasMobilityIssues?: boolean;
  diaperSize?: string;
  notificationPreference?: string;
  phone?: string;
  phoneCarrier?: string;
  location?: string;
  program?: string; // Link2Feed Program field
  clientType?: string;
  waitTime?: number;
  
  // Appointment data
  pickUpDate?: string;
  pickUpISO?: string;
  provisions?: string;
  quantity?: number;
  
  // Next appointment data
  nextAppointmentDate?: string;
  nextAppointmentTime?: string;
  nextAppointmentISO?: string;
  ticketNumber?: string;
  isAutoGenerated?: boolean;
  generatedFrom?: string;
  generatedAt?: string;
  
  // Metadata
  createdAt: string;
  updatedAt: string;
  expiresAt: string;
}

const CheckInsPage: React.FC = () => {
  const [checkIns, setCheckIns] = useState<CheckInRecord[]>([]);
  const [filteredCheckIns, setFilteredCheckIns] = useState<CheckInRecord[]>([]);
  const [searchTerm, setSearchTerm] = useState('');
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [selectedCheckIn, setSelectedCheckIn] = useState<CheckInRecord | null>(null);
  const { isOpen: isDetailOpen, onOpen: onDetailOpen, onClose: onDetailClose } = useDisclosure();


  // Fetch today's CSV appointments and filter to 8 AM – 8 PM window (local/Vancouver time)
  const fetchCheckIns = async () => {
    try {
      setIsLoading(true);
      setError(null);
      
      // Use appointments endpoint to ensure CSV-sourced records are included
      const response = await fetch(getApiUrl('/checkin/appointments'));
      const data = await response.json();

      if (data.success && Array.isArray(data.data)) {
        const now = new Date();
        // Build today's date for filtering in local time (fallback if ISO missing)
        const y = now.getFullYear();
        const m = String(now.getMonth() + 1).padStart(2, '0');
        const d = String(now.getDate()).padStart(2, '0');
        const todayStr = `${y}-${m}-${d}`;

        const inWindow = (rec: any) => {
          const iso = rec.pickUpISO || rec.appointmentTime;
          const timeStr = rec.pickUpTime; // e.g., HH:MM
          let dt: Date | null = null;

          if (iso) {
            const parsed = new Date(iso);
            if (!isNaN(parsed.getTime())) dt = parsed;
          }
          if (!dt && typeof timeStr === 'string' && timeStr.match(/^\d{2}:\d{2}$/)) {
            dt = new Date(`${todayStr}T${timeStr}:00`);
          }

          if (!dt) return false;

          // Ensure it's today
          const sameDay = dt.getFullYear() === now.getFullYear() && dt.getMonth() === now.getMonth() && dt.getDate() === now.getDate();
          if (!sameDay) return false;

          const hour = dt.getHours();
          return hour >= 8 && hour < 20; // 08:00 inclusive to 20:00 exclusive
        };

        const filtered = (data.data as any[]).filter(inWindow);
        setCheckIns(filtered);
        setFilteredCheckIns(filtered);
      } else {
        setError('No check-ins data available');
        setCheckIns([]);
        setFilteredCheckIns([]);
      }
    } catch (err) {
      console.error('Failed to fetch check-ins:', err);
      setError('Failed to load check-ins data');
      setCheckIns([]);
      setFilteredCheckIns([]);
    } finally {
      setIsLoading(false);
    }
  };

  // Filter check-ins based on search
  useEffect(() => {
    let filtered = checkIns;

    // Filter by search term
    if (searchTerm) {
      const search = searchTerm.toLowerCase();
      filtered = filtered.filter(checkIn => 
        checkIn.clientName.toLowerCase().includes(search) ||
        checkIn.clientId.toLowerCase().includes(search) ||
        checkIn.phoneNumber.includes(search) ||
        checkIn.firstName?.toLowerCase().includes(search) ||
        checkIn.lastName?.toLowerCase().includes(search)
      );
    }

    setFilteredCheckIns(filtered);
  }, [checkIns, searchTerm]);

  // Initial fetch
  useEffect(() => {
    fetchCheckIns();
  }, []);

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'Collected':
        return 'green';
      case 'Shipped':
        return 'purple';
      case 'Pending':
        return 'yellow';
      case 'Not Collected':
        return 'red';
      case 'Rescheduled':
        return 'orange';
      case 'Cancelled':
        return 'gray';
      default:
        return 'gray';
    }
  };

  const getStatusText = (status: string, checkIn: CheckInRecord) => {
    // Check if appointment is late or missed
    if (status === 'Pending' && checkIn.appointmentTime) {
      const appointmentTime = new Date(checkIn.appointmentTime);
      const now = new Date();
      const hoursPast = (now.getTime() - appointmentTime.getTime()) / (1000 * 60 * 60);
      
      if (hoursPast >= 4) {
        return 'Missed';
      } else if (hoursPast >= 1) {
        const hours = Math.floor(hoursPast);
        const minutes = Math.floor((hoursPast - hours) * 60);
        if (minutes > 0) {
          return `Late by ${hours}h ${minutes}m`;
        } else {
          return `Late by ${hours}h`;
        }
      }
    }
    
    switch (status) {
      case 'Collected':
        return 'Completed';
      case 'Shipped':
        return 'In Transit';
      case 'Pending':
        return 'Pending';
      case 'Not Collected':
        return 'Not Collected';
      case 'Rescheduled':
        return 'Rescheduled';
      case 'Cancelled':
        return 'Cancelled';
      default:
        return 'Unknown';
    }
  };

  const handlePrintTicket = (checkIn: CheckInRecord) => {
    if (checkIn.clientId) {
      window.open(getApiUrl(`/tickets/${checkIn.id}`), '_blank');
    }
  };

  const handleViewDetails = (checkIn: CheckInRecord) => {
    setSelectedCheckIn(checkIn);
    onDetailOpen();
  };

  const handleCancelAppointment = async (checkIn: CheckInRecord) => {
    try {
      const response = await fetch(getApiUrl(`/checkin/${checkIn.id}/status`), {
        method: 'PUT',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          status: 'Cancelled',
          notes: 'Cancelled by admin'
        })
      });
      
      if (response.ok) {
        // Refresh the data
        await fetchCheckIns();
      } else {
        console.error('Failed to cancel appointment');
      }
    } catch (error) {
      console.error('Error cancelling appointment:', error);
    }
  };

  const handleExportCSV = async () => {
    try {
      const response = await fetch(getApiUrl('/csv/export-next-appointments'));
      
      if (response.ok) {
        const blob = await response.blob();
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `next-appointments-${new Date().toISOString().split('T')[0]}.csv`;
        document.body.appendChild(a);
        a.click();
        window.URL.revokeObjectURL(url);
        document.body.removeChild(a);
      } else {
        console.error('Failed to export CSV');
      }
    } catch (error) {
      console.error('Error exporting CSV:', error);
    }
  };

  if (isLoading) {
    return (
      <Box p={6}>
        <VStack spacing={6} align="stretch">
          <HStack justify="space-between">
            <Skeleton height="32px" width="200px" />
            <Skeleton height="40px" width="120px" />
          </HStack>
          <Skeleton height="60px" width="100%" />
          <VStack spacing={4} align="stretch">
            {[1, 2, 3, 4, 5].map((i) => (
              <Card key={i}>
                <CardBody>
                  <HStack spacing={4}>
                    <SkeletonCircle size="40px" />
                    <VStack align="start" spacing={2} flex={1}>
                      <Skeleton height="20px" width="200px" />
                      <Skeleton height="16px" width="150px" />
                    </VStack>
                    <Skeleton height="24px" width="80px" />
                  </HStack>
                </CardBody>
              </Card>
            ))}
          </VStack>
        </VStack>
      </Box>
    );
  }

  return (
    <Box>
      {/* Header Section */}
      <Box mb={{ base: 4, md: 6, lg: 8 }} position="relative">
        {/* Header */}
        <VStack 
          spacing={{ base: 4, md: 6 }} 
          align={{ base: "stretch", lg: "flex-start" }}
          mb={6}
        >
          <VStack align="start" spacing={{ base: 2, md: 4 }} w="full">
            <Heading 
              size="xl" 
              color="admin.primary"
              fontWeight="700"
              textAlign="center"
              w="full"
              letterSpacing="-0.025em"
            >
              Client Check-ins
            </Heading>
            <Text 
              color="gray.600" 
              fontSize="lg"
              maxW="600px"
              textAlign="center"
              w="full"
              mx="auto"
              fontWeight="500"
            >
              Manage and view all client check-ins for today
            </Text>
          </VStack>
          
          <VStack 
            spacing={{ base: 3, md: 4 }} 
            align={{ base: "center", lg: "end" }}
            w="full"
            maxW={{ base: "100%", lg: "auto" }}
          >
            <HStack spacing={3}>
              <Button
                size={{ base: "sm", sm: "md" }}
                variant="outline"
                leftIcon={<FiDownload />}
                onClick={handleExportCSV}
                w={{ base: "full", sm: "auto" }}
                maxW={{ base: "280px", sm: "none" }}
              >
                Export Next Appointments
              </Button>
              <Button
                size={{ base: "sm", sm: "md" }}
                variant="outline"
                leftIcon={<FiRefreshCw />}
                onClick={fetchCheckIns}
                isLoading={isLoading}
                w={{ base: "full", sm: "auto" }}
                maxW={{ base: "280px", sm: "none" }}
              >
                Refresh Data
              </Button>
            </HStack>
          </VStack>
        </VStack>
      </Box>

      {/* Statistics Section */}
      <Box mb={{ base: 4, md: 6 }}>
        <Heading 
          size="lg" 
          color="admin.primary" 
          mb={4} 
          textAlign="center" 
          fontWeight="semibold"
        >
          Check-in Statistics
        </Heading>
        <Grid 
          templateColumns={{ base: "1fr", md: "repeat(4, 1fr)" }}
          gap={4}
          mb={3}
          alignItems="stretch"
          w="full"
          maxW="1200px"
          mx="auto"
          minH="0"
        >
          <Box 
            bg="white"
            borderRadius="xl"
            boxShadow="lg"
            border="2px solid"
            borderColor="gray.300"
            p={5}
          >
            <VStack align="center" spacing={2}>
              <Text fontSize="2xl" fontWeight="bold" color="admin.primary">
                {checkIns.length}
              </Text>
              <Text fontSize="sm" color="gray.600" textAlign="center">
                Total Appointments
              </Text>
            </VStack>
          </Box>
          <Box 
            bg="white"
            borderRadius="2xl"
            boxShadow="0 10px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)"
            p={6}
            position="relative"
            _before={{
              content: '""',
              position: 'absolute',
              top: 0,
              left: 0,
              right: 0,
              height: '4px',
              background: '#8CAB6D',
              borderRadius: '2xl 2xl 0 0',
            }}
          >
            <VStack align="center" spacing={3}>
              <Text fontSize="3xl" fontWeight="bold" color="#8CAB6D">
                {checkIns.filter(c => c.status === 'Collected').length}
              </Text>
              <Text fontSize="md" color="gray.600" textAlign="center" fontWeight="500">
                Completed
              </Text>
            </VStack>
          </Box>
          <Box 
            bg="white"
            borderRadius="2xl"
            boxShadow="0 10px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)"
            p={6}
            position="relative"
            _before={{
              content: '""',
              position: 'absolute',
              top: 0,
              left: 0,
              right: 0,
              height: '4px',
              background: '#2B7B8C',
              borderRadius: '2xl 2xl 0 0',
            }}
          >
            <VStack align="center" spacing={3}>
              <Text fontSize="3xl" fontWeight="bold" color="#2B7B8C">
                {checkIns.filter(c => c.status === 'Pending' && c.checkInTime).length}
              </Text>
              <Text fontSize="md" color="gray.600" textAlign="center" fontWeight="500">
                Checked In
              </Text>
            </VStack>
          </Box>
          <Box 
            bg="white"
            borderRadius="2xl"
            boxShadow="0 10px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)"
            p={6}
            position="relative"
            _before={{
              content: '""',
              position: 'absolute',
              top: 0,
              left: 0,
              right: 0,
              height: '4px',
              background: '#F4A261',
              borderRadius: '2xl 2xl 0 0',
            }}
          >
            <VStack align="center" spacing={3}>
              <Text fontSize="3xl" fontWeight="bold" color="#F4A261">
                {checkIns.filter(c => c.status === 'Pending').length}
              </Text>
              <Text fontSize="md" color="gray.600" textAlign="center" fontWeight="500">
                Pending
              </Text>
            </VStack>
          </Box>
        </Grid>
      </Box>

      {/* Search Section */}
      <Box mb={{ base: 4, md: 6 }}>
        <Heading 
          size="lg" 
          color="admin.primary" 
          mb={4} 
          textAlign="center" 
          fontWeight="semibold"
        >
          Search & Filter
        </Heading>
        <Box 
          bg="white"
          borderRadius="xl"
          boxShadow="lg"
          border="2px solid"
          borderColor="gray.300"
          p={5}
          w="full"
          maxW="1200px"
          mx="auto"
        >
          <VStack spacing={4} align="stretch">
            <HStack spacing={2}>
              <FiSearch color="#718096" />
              <Input
                placeholder="Search by name, ID, or phone..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                flex={1}
                border="none"
                _focus={{ boxShadow: 'none' }}
              />
            </HStack>
          </VStack>
        </Box>
      </Box>

      {/* Check-ins List Section */}
      <Box mt={4}>
        <Heading 
          size="lg" 
          color="admin.primary" 
          mb={3} 
          textAlign="center" 
          fontWeight="semibold"
        >
          Client Check-ins
        </Heading>
        
        {/* Error State */}
        {error && (
          <Alert status="error" borderRadius="md">
            <AlertIcon />
            <Box>
              <Text fontWeight="bold" mb={2}>
                {error}
              </Text>
            </Box>
          </Alert>
        )}

        {/* Check-ins List */}
        <Box 
          w="full"
          maxW="1200px"
          mx="auto"
        >
          {filteredCheckIns.length === 0 ? (
          <Box 
            bg="white"
            borderRadius="xl"
            boxShadow="lg"
            border="2px solid"
            borderColor="gray.300"
            p={8}
          >
            <Center py={8}>
              <VStack spacing={4}>
                <Box
                  p={4}
                  bg="gray.50"
                  borderRadius="full"
                  color="gray.400"
                >
                  <FiUsers size="32px" />
                </Box>
                <VStack spacing={1}>
                  <Text fontSize="md" fontWeight="500" color="gray.600">
                    No check-ins found
                  </Text>
                  <Text fontSize="sm" color="gray.500">
                    {searchTerm 
                      ? 'Try adjusting your search'
                      : 'Upload a CSV file to get started'
                    }
                  </Text>
                </VStack>
              </VStack>
            </Center>
          </Box>
        ) : (
          <VStack spacing={4} align="stretch">
            {filteredCheckIns.map((checkIn) => (
              <Box 
                key={checkIn.id} 
                bg="white"
                borderRadius="xl"
                boxShadow="lg"
                border="2px solid"
                borderColor="gray.300"
                p={5}
                _hover={{ shadow: 'xl', transform: 'translateY(-2px)' }} 
                transition="all 0.2s"
              >
                  <HStack spacing={4} align="start">
                    <Avatar
                      name={checkIn.clientName}
                      size="md"
                      bg="brand.500"
                      color="white"
                    />
                    
                    <VStack align="start" spacing={2} flex={1}>
                      <HStack spacing={3} wrap="wrap">
                        <HStack spacing={2} align="center">
                          <Box
                            px={2}
                            py={1}
                            borderRadius="sm"
                            fontSize="xs"
                            fontWeight="600"
                            color="white"
                            bg={getStatusColor(checkIn.status) === 'green' ? '#8CAB6D' : 
                                 getStatusColor(checkIn.status) === 'yellow' ? '#F4A261' : 
                                 getStatusColor(checkIn.status) === 'red' ? '#E53E3E' : '#718096'}
                          >
                            {getStatusText(checkIn.status, checkIn)}
                          </Box>
                          <Text fontSize="lg" fontWeight="600" color="gray.900">
                            {checkIn.clientName}
                          </Text>
                        </HStack>
                        <Badge colorScheme="gray" variant="subtle" fontSize="xs">
                          ID: {checkIn.clientId}
                        </Badge>
                        {checkIn.hasMobilityIssues && (
                          <Tooltip label="Mobility Assistance Required" placement="top">
                            <Box color="#F4A261" cursor="help" fontSize="16px">
                              ♿
                            </Box>
                          </Tooltip>
                        )}
                      </HStack>
                      
                      <HStack spacing={4} wrap="wrap">
                        <HStack spacing={1}>
                          <FiClock size={14} color="#718096" />
                          <Text fontSize="sm" color="gray.600">
                            {checkIn.checkInTime 
                              ? `Checked in ${formatDistanceToNow(new Date(checkIn.checkInTime), { addSuffix: true })}`
                              : checkIn.appointmentTime 
                                ? `Appointment: ${formatToVancouverTimeOnly(checkIn.appointmentTime)}`
                                : 'No time available'
                            }
                          </Text>
                        </HStack>
                        
                        {checkIn.phoneNumber && (
                          <HStack spacing={1}>
                            <FiPhone size={14} color="#718096" />
                            <Text fontSize="sm" color="gray.600">
                              {formatPhoneNumber(checkIn.phoneNumber)}
        </Text>
                          </HStack>
                        )}
                        
                        {checkIn.email && (
                          <HStack spacing={1}>
                            <FiMail size={14} color="#718096" />
                            <Text fontSize="sm" color="gray.600">
                              {checkIn.email}
        </Text>
                          </HStack>
                        )}
                      </HStack>

                      {/* Additional Info */}
                      <HStack spacing={4} wrap="wrap" fontSize="sm" color="gray.500">
                        {checkIn.householdSize && (
                          <Text>Household: {checkIn.householdSize} people</Text>
                        )}
                        {checkIn.dietaryConsiderations && (
                          <Text>Dietary: {checkIn.dietaryConsiderations}</Text>
                        )}
                        {checkIn.location && (
                          <Text>Location: {checkIn.location}</Text>
                        )}
                        {checkIn.program && (
                          <Text>Program: {checkIn.program}</Text>
                        )}
                      </HStack>
                    </VStack>
                    
                    <VStack spacing={2} align="end">
                      <HStack spacing={1}>
                        <Tooltip label="View Details" placement="top">
                          <IconButton
                            size="sm"
                            variant="ghost"
                            color="gray.500"
                            _hover={{ color: 'blue.500', bg: 'blue.50' }}
                            onClick={() => handleViewDetails(checkIn)}
                            icon={<FiEye size="16px" />}
                            aria-label="View Details"
                          />
                        </Tooltip>
                        
                        <Tooltip 
                          label="Print Ticket (Opens in new window for landscape printing)" 
                          placement="top"
                        >
                          <IconButton
                            size="sm"
                            variant="ghost"
                            color="gray.500"
                            _hover={{ color: 'blue.500', bg: 'blue.50' }}
                            onClick={() => handlePrintTicket(checkIn)}
                            icon={<FiPrinter size="16px" />}
                            aria-label="Print Ticket"
                          />
                        </Tooltip>

                        {checkIn.status === 'Pending' && (
                          <Tooltip label="Cancel Appointment" placement="top">
                            <IconButton
                              size="sm"
                              variant="ghost"
                              color="gray.500"
                              _hover={{ color: 'red.500', bg: 'red.50' }}
                              onClick={() => handleCancelAppointment(checkIn)}
                              icon={<FiX size="16px" />}
                              aria-label="Cancel Appointment"
                            />
                          </Tooltip>
                        )}
                      </HStack>
                    </VStack>
                  </HStack>
              </Box>
            ))}
          </VStack>
          )}
        </Box>
      </Box>

        {/* Detail Modal */}
        <Modal isOpen={isDetailOpen} onClose={onDetailClose} size="xl">
          <ModalOverlay />
          <ModalContent>
            <ModalHeader>Client Details</ModalHeader>
            <ModalCloseButton />
            <ModalBody>
              {selectedCheckIn && (
                <VStack spacing={4} align="stretch">
                  {/* Basic Info */}
                  <Card>
                    <CardHeader>
                      <Text fontSize="lg" fontWeight="600">Basic Information</Text>
                    </CardHeader>
                    <CardBody>
                      <Grid templateColumns="repeat(2, 1fr)" gap={4}>
                        <VStack align="start" spacing={2}>
                          <Text><strong>Name:</strong> {selectedCheckIn.clientName}</Text>
                          <Text><strong>Client ID:</strong> {selectedCheckIn.clientId}</Text>
                          <Text><strong>Phone:</strong> {formatPhoneNumber(selectedCheckIn.phoneNumber)}</Text>
                          {selectedCheckIn.email && (
                            <Text><strong>Email:</strong> {selectedCheckIn.email}</Text>
                          )}
                          <Text><strong>Next Appointment:</strong> {selectedCheckIn.nextAppointmentISO ? formatToVancouverTime(selectedCheckIn.nextAppointmentISO) : 'No next appointment scheduled'}</Text>
                          {selectedCheckIn.ticketNumber && (
                            <Text><strong>Ticket #:</strong> {selectedCheckIn.ticketNumber}</Text>
                          )}
                          {selectedCheckIn.isAutoGenerated && (
                            <Text fontSize="sm" color="blue.600"><strong>✓ Auto-scheduled (21 days)</strong></Text>
                          )}
                        </VStack>
                        <VStack align="start" spacing={2}>
                          <Text><strong>Status:</strong> {getStatusText(selectedCheckIn.status, selectedCheckIn)}</Text>
                          <Text><strong>Check-in Time:</strong> {selectedCheckIn.checkInTime ? formatToVancouverTime(selectedCheckIn.checkInTime) : 'Not checked in'}</Text>
                          <Text><strong>Appointment Time:</strong> {selectedCheckIn.appointmentTime ? formatToVancouverTime(selectedCheckIn.appointmentTime) : 'No appointment'}</Text>
                          <Text><strong>Reminder Preference:</strong> {selectedCheckIn.notificationPreference || 'Email'}</Text>
                          {selectedCheckIn.hasMobilityIssues && (
                            <Text color="#F4A261"><strong>♿ Mobility Assistance Required</strong></Text>
                          )}
                        </VStack>
                      </Grid>
                    </CardBody>
                  </Card>

                  {/* Household Info */}
                  <Card>
                    <CardHeader>
                      <Text fontSize="lg" fontWeight="600">Household Information</Text>
                    </CardHeader>
                    <CardBody>
                      <Grid templateColumns="repeat(2, 1fr)" gap={4}>
                        <VStack align="start" spacing={2}>
                          <Text><strong>Household Size:</strong> {selectedCheckIn.householdSize || 'Not specified'}</Text>
                          <Text><strong>Adults:</strong> {selectedCheckIn.adults || 'Not specified'}</Text>
                          <Text><strong>Seniors:</strong> {selectedCheckIn.seniors || 'Not specified'}</Text>
                          <Text><strong>Children:</strong> {selectedCheckIn.children || 'Not specified'}</Text>
                        </VStack>
                        <VStack align="start" spacing={2}>
                          {selectedCheckIn.childrensAges && (
                            <Text><strong>Children's Ages:</strong> {selectedCheckIn.childrensAges}</Text>
                          )}
                          <Text><strong>Location:</strong> {selectedCheckIn.location || 'Food Bank Location'}</Text>
                          <Text><strong>Program:</strong> {selectedCheckIn.program || 'Food Hamper'}</Text>
                          <Text><strong>Client Type:</strong> {selectedCheckIn.clientType || 'Not specified'}</Text>
                        </VStack>
                      </Grid>
                    </CardBody>
                  </Card>

                  {/* Dietary & Special Needs */}
                  <Card>
                    <CardHeader>
                      <Text fontSize="lg" fontWeight="600">Dietary & Special Needs</Text>
                    </CardHeader>
                    <CardBody>
                      <VStack align="start" spacing={2}>
                        {selectedCheckIn.dietaryConsiderations && (
                          <Text><strong>Dietary Considerations:</strong> {selectedCheckIn.dietaryConsiderations}</Text>
                        )}
                        {selectedCheckIn.dietaryRestrictions && selectedCheckIn.dietaryRestrictions.length > 0 && (
                          <Text><strong>Dietary Restrictions:</strong> {selectedCheckIn.dietaryRestrictions.join(', ')}</Text>
                        )}
                        {selectedCheckIn.allergies && (
                          <Text><strong>Allergies:</strong> {selectedCheckIn.allergies}</Text>
                        )}
                        {selectedCheckIn.unwantedFoods && (
                          <Text><strong>Unwanted Foods:</strong> {selectedCheckIn.unwantedFoods}</Text>
                        )}
                        {selectedCheckIn.diaperSize && (
                          <Text><strong>Diaper Size:</strong> {selectedCheckIn.diaperSize}</Text>
                        )}
                      </VStack>
                    </CardBody>
                  </Card>

                  {/* Additional Info */}
                  {(selectedCheckIn.additionalInfo || selectedCheckIn.notes) && (
                    <Card>
                      <CardHeader>
                        <Text fontSize="lg" fontWeight="600">Additional Information</Text>
                      </CardHeader>
                      <CardBody>
                        <VStack align="start" spacing={2}>
                          {selectedCheckIn.additionalInfo && (
                            <Text><strong>Additional Info:</strong> {selectedCheckIn.additionalInfo}</Text>
                          )}
                          {selectedCheckIn.notes && (
                            <Text><strong>Notes:</strong> {selectedCheckIn.notes}</Text>
                          )}
                        </VStack>
                      </CardBody>
                    </Card>
                  )}
                </VStack>
              )}
            </ModalBody>
            <ModalFooter>
              <Button variant="outline" mr={3} onClick={onDetailClose}>
                Close
              </Button>
              <Tooltip 
                label="Opens ticket in new window. Set printer to Landscape orientation for best results."
                placement="left"
              >
                <Button colorScheme="blue" onClick={() => {
                  if (selectedCheckIn) {
                    handlePrintTicket(selectedCheckIn);
                  }
                }}>
                  Print Ticket
                </Button>
              </Tooltip>
            </ModalFooter>
          </ModalContent>
        </Modal>
    </Box>
  );
};

export default CheckInsPage;
