/**
 * @fileoverview Detail modal for a check-in record
 */

import React from 'react';
import {
  Button,
  Card,
  CardBody,
  CardHeader,
  Grid,
  Modal,
  ModalBody,
  ModalCloseButton,
  ModalContent,
  ModalFooter,
  ModalHeader,
  ModalOverlay,
  Text,
  VStack,
} from '@chakra-ui/react';
import PrintTicketButton from '../../ui/PrintTicketButton';
import { CheckInRecord } from '../../../types/checkIn';
import { formatToVancouverTime } from '../../../utils/timeFormatter';
import { formatPhoneNumber } from '../../../utils/phoneFormatter';
import { getStatusText } from './checkInUtils';

interface CheckInDetailModalProps {
  isOpen: boolean;
  onClose: () => void;
  checkIn: CheckInRecord | null;
  onPrintTicket: (checkIn: CheckInRecord) => void;
}

const CheckInDetailModal: React.FC<CheckInDetailModalProps> = ({
  isOpen,
  onClose,
  checkIn,
  onPrintTicket,
}) => {
  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      size={{ base: 'full', md: 'xl' }}
      scrollBehavior="inside"
      isCentered
    >
      <ModalOverlay />
      <ModalContent maxH={{ base: '100vh', md: '90vh' }}>
        <ModalHeader fontSize={{ base: 'lg', md: 'xl' }}>Client Details</ModalHeader>
        <ModalCloseButton />
        <ModalBody>
          {checkIn && (
            <VStack spacing={4} align="stretch">
              <Card>
                <CardHeader>
                  <Text fontSize="lg" fontWeight="600">
                    Basic Information
                  </Text>
                </CardHeader>
                <CardBody>
                  <Grid templateColumns={{ base: '1fr', md: 'repeat(2, 1fr)' }} gap={{ base: 3, md: 4 }}>
                    <VStack align="start" spacing={2}>
                      <Text>
                        <strong>Name:</strong> {checkIn.clientName}
                      </Text>
                      <Text>
                        <strong>Client ID:</strong> {checkIn.clientId}
                      </Text>
                      <Text>
                        <strong>Phone:</strong> {formatPhoneNumber(checkIn.phoneNumber)}
                      </Text>
                      {checkIn.email && (
                        <Text>
                          <strong>Email:</strong> {checkIn.email}
                        </Text>
                      )}
                      <Text>
                        <strong>Next Appointment:</strong>{' '}
                        {checkIn.nextAppointmentISO
                          ? formatToVancouverTime(checkIn.nextAppointmentISO)
                          : 'No next appointment scheduled'}
                      </Text>
                      {checkIn.ticketNumber && (
                        <Text>
                          <strong>Ticket #:</strong> {checkIn.ticketNumber}
                        </Text>
                      )}
                      {checkIn.isAutoGenerated && (
                        <Text fontSize="sm" color="blue.600">
                          <strong>✓ Auto-scheduled (21 days)</strong>
                        </Text>
                      )}
                    </VStack>
                    <VStack align="start" spacing={2}>
                      <Text>
                        <strong>Status:</strong> {getStatusText(checkIn.status, checkIn)}
                      </Text>
                      <Text>
                        <strong>Check-in Time:</strong>{' '}
                        {checkIn.checkInTime ? formatToVancouverTime(checkIn.checkInTime) : 'Not checked in'}
                      </Text>
                      <Text>
                        <strong>Appointment Time:</strong>{' '}
                        {checkIn.appointmentTime
                          ? formatToVancouverTime(checkIn.appointmentTime)
                          : 'No appointment'}
                      </Text>
                      <Text>
                        <strong>Reminder Preference:</strong> {checkIn.notificationPreference || 'Email'}
                      </Text>
                      {checkIn.hasMobilityIssues && (
                        <Text color="accent.orange.300">
                          <strong>♿ Mobility Assistance Required</strong>
                        </Text>
                      )}
                    </VStack>
                  </Grid>
                </CardBody>
              </Card>

              <Card>
                <CardHeader>
                  <Text fontSize="lg" fontWeight="600">
                    Household Information
                  </Text>
                </CardHeader>
                <CardBody>
                  <Grid templateColumns={{ base: '1fr', md: 'repeat(2, 1fr)' }} gap={{ base: 3, md: 4 }}>
                    <VStack align="start" spacing={2}>
                      <Text>
                        <strong>Household Size:</strong> {checkIn.householdSize || 'Not specified'}
                      </Text>
                      <Text>
                        <strong>Adults:</strong> {checkIn.adults || 'Not specified'}
                      </Text>
                      <Text>
                        <strong>Seniors:</strong> {checkIn.seniors || 'Not specified'}
                      </Text>
                      <Text>
                        <strong>Children:</strong> {checkIn.children || 'Not specified'}
                      </Text>
                    </VStack>
                    <VStack align="start" spacing={2}>
                      {checkIn.childrensAges && (
                        <Text>
                          <strong>Children's Ages:</strong> {checkIn.childrensAges}
                        </Text>
                      )}
                      <Text>
                        <strong>Location:</strong> {checkIn.location || 'Food Bank Location'}
                      </Text>
                      <Text>
                        <strong>Program:</strong> {checkIn.program || 'Food Hamper'}
                      </Text>
                      <Text>
                        <strong>Client Type:</strong> {checkIn.clientType || 'Not specified'}
                      </Text>
                    </VStack>
                  </Grid>
                </CardBody>
              </Card>

              <Card>
                <CardHeader>
                  <Text fontSize="lg" fontWeight="600">
                    Dietary & Special Needs
                  </Text>
                </CardHeader>
                <CardBody>
                  <VStack align="start" spacing={2}>
                    {checkIn.dietaryConsiderations && (
                      <Text>
                        <strong>Dietary Considerations:</strong> {checkIn.dietaryConsiderations}
                      </Text>
                    )}
                    {checkIn.dietaryRestrictions && checkIn.dietaryRestrictions.length > 0 && (
                      <Text>
                        <strong>Dietary Restrictions:</strong> {checkIn.dietaryRestrictions.join(', ')}
                      </Text>
                    )}
                    {checkIn.allergies && (
                      <Text>
                        <strong>Allergies:</strong> {checkIn.allergies}
                      </Text>
                    )}
                    {checkIn.unwantedFoods && (
                      <Text>
                        <strong>Unwanted Foods:</strong> {checkIn.unwantedFoods}
                      </Text>
                    )}
                    {checkIn.diaperSize && (
                      <Text>
                        <strong>Diaper Size:</strong> {checkIn.diaperSize}
                      </Text>
                    )}
                  </VStack>
                </CardBody>
              </Card>

              {(checkIn.additionalInfo || checkIn.notes) && (
                <Card>
                  <CardHeader>
                    <Text fontSize="lg" fontWeight="600">
                      Additional Information
                    </Text>
                  </CardHeader>
                  <CardBody>
                    <VStack align="start" spacing={2}>
                      {checkIn.additionalInfo && (
                        <Text>
                          <strong>Additional Info:</strong> {checkIn.additionalInfo}
                        </Text>
                      )}
                      {checkIn.notes && (
                        <Text>
                          <strong>Notes:</strong> {checkIn.notes}
                        </Text>
                      )}
                    </VStack>
                  </CardBody>
                </Card>
              )}
            </VStack>
          )}
        </ModalBody>
        <ModalFooter>
          <Button variant="outline" mr={3} onClick={onClose}>
            Close
          </Button>
          <PrintTicketButton
            variant="full"
            onClick={() => { if (checkIn) onPrintTicket(checkIn); }}
            isDisabled={!checkIn}
          />
        </ModalFooter>
      </ModalContent>
    </Modal>
  );
};

export default CheckInDetailModal;
