/**
 * @fileoverview CSV controller for Foodbank Check-In and Appointment System backend API
 * 
 * This module handles CSV file processing operations including file upload,
 * data validation, and bulk appointment creation. It provides methods for
 * processing CSV data and managing bulk operations for the food bank system.
 * 
 * @author Lindsey D. Stead
 * @version 1.0.0
 * @since 2025-10-20
 * @license Proprietary - see LICENSE file for details
 * 
 * @see {@link ../services/csvProcessor.ts} CSV processing service
 */

import { getTodayAppointments, getAllCheckIns } from '../stores/unifiedStore';

export class CsvController {
  // Note: Most methods removed - only using exportNextAppointments now
  // Legacy methods kept in case needed for future admin features

  /**
   * Export next appointments as CSV
   * @returns CSV string with next appointment data
   */
  static exportNextAppointments(): string {
    const checkIns = getAllCheckIns();
    const completedCheckIns = checkIns.filter(c => c.status === 'Collected' && c.nextAppointmentISO);
    
    // CSV headers
    const headers = [
      'Pick Up Date',
      'Client ID',
      'Client Name',
      'Phone Number',
      'Email',
      'Household Size',
      'Adults',
      'Seniors',
      'Children',
      'Children Ages',
      'Dietary Considerations',
      'Location',
      'Program',
      'Next Appointment Date',
      'Next Appointment Time',
      'Next Appointment ISO',
      'Ticket Number',
      'Is Auto Generated',
      'Generated At'
    ];
    
    // Helper to format "YYYY-MM-DD @ h:mm AM/PM" in local time
    const formatPickUpDisplay = (iso?: string, date?: string, time?: string): string => {
      try {
        if (iso) {
          const d = new Date(iso);
          if (!isNaN(d.getTime())) {
            const yyyy = d.getFullYear();
            const mm = String(d.getMonth() + 1).padStart(2, '0');
            const dd = String(d.getDate()).padStart(2, '0');
            let hours = d.getHours();
            const minutes = String(d.getMinutes()).padStart(2, '0');
            const ampm = hours >= 12 ? 'PM' : 'AM';
            hours = hours % 12;
            if (hours === 0) hours = 12;
            return `${yyyy}-${mm}-${dd} @ ${hours}:${minutes} ${ampm}`;
          }
        }
        if (date && time) return `${date} @ ${time}`;
        if (date) return `${date}`;
      } catch {}
      return '';
    };

    // Convert to CSV rows
    const rows = completedCheckIns.map(checkIn => [
      formatPickUpDisplay(checkIn.nextAppointmentISO, checkIn.nextAppointmentDate, checkIn.nextAppointmentTime),
      checkIn.clientId,
      checkIn.clientName,
      checkIn.phoneNumber || '',
      checkIn.email || '',
      checkIn.householdSize || '',
      checkIn.adults || '',
      checkIn.seniors || '',
      checkIn.children || '',
      checkIn.childrensAges || checkIn.childrenAges || '',
      checkIn.dietaryConsiderations || '',
      checkIn.location || 'Foodbank Check-In and Appointment System',
      checkIn.program || 'Food Hamper',
      checkIn.nextAppointmentDate || '',
      checkIn.nextAppointmentTime || '',
      checkIn.nextAppointmentISO || '',
      checkIn.ticketNumber || '',
      checkIn.isAutoGenerated ? 'Yes' : 'No',
      checkIn.generatedAt || ''
    ]);
    
    // Combine headers and rows
    const csvContent = [headers, ...rows]
      .map(row => row.map(field => `"${String(field).replace(/"/g, '""')}"`).join(','))
      .join('\n');
    
    return csvContent;
  }
}

export default CsvController;
