/**
 * @fileoverview Simplified appointment date editing routes for Foodbank Check-In and Appointment System backend API
 * 
 * This module handles updating next appointment dates for clients.
 * It focuses solely on updating the appointment date that appears on printed tickets.
 * 
 * @author Lindsey D. Stead
 * @version 1.0.0
 * @since 2025-10-20
 * @license Proprietary - see LICENSE file for details
 * 
 * @see {@link ../controllers/checkInController.ts} Check-in controller
 */

import { Router } from 'express';
import { getTodayAppointments, updateCheckIn, getCheckInById } from '../stores/unifiedStore';
import dayjs from 'dayjs';
import timezone from 'dayjs/plugin/timezone';
import utc from 'dayjs/plugin/utc';

// Extend dayjs with timezone support
dayjs.extend(utc);
dayjs.extend(timezone);

const router = Router();

/**
 * PUT /api/admin/appointments/:checkInId/update-next-date
 * Update the next appointment date for a check-in record
 * 
 * IMPORTANT: Uses checkInId (not clientId) to ensure we update the correct check-in record.
 * This ensures the update applies to the specific check-in and appears on tickets.
 */
router.put('/appointments/:checkInId/update-next-date', (req, res) => {
  try {
    const { checkInId } = req.params;
    const { newDate, newTime } = req.body as { newDate?: string; newTime?: string };
    
    // Validate required fields
    if (!newDate) {
      return res.status(400).json({
        success: false,
        error: 'New date is required'
      });
    }
    
    // Build ISO using provided time or default 10:00
    const time = typeof newTime === 'string' && /^\d{2}:\d{2}$/.test(newTime) ? newTime : '10:00';
    
    // IMPORTANT: Use Vancouver timezone for ISO string to match system timezone
    const VANCOUVER_TZ = 'America/Vancouver';
    const isoString = dayjs.tz(`${newDate}T${time}:00`, VANCOUVER_TZ).toISOString();
    
    // Get the specific check-in record by ID (more reliable than clientId)
    const currentCheckIn = getCheckInById(checkInId);
    
    if (!currentCheckIn) {
      return res.status(404).json({
        success: false,
        error: 'Check-in record not found'
      });
    }
    
    // IMPORTANT: Update the next appointment date fields in the check-in record
    // This ensures the update appears on tickets and throughout the app
    const updatedCheckIn = updateCheckIn(checkInId, {
      nextAppointmentDate: newDate,
      nextAppointmentTime: time,
      nextAppointmentISO: isoString,
      // Mark as manually updated (not auto-generated)
      isAutoGenerated: false,
      updatedAt: new Date().toISOString()
    });
    
    if (!updatedCheckIn) {
      return res.status(500).json({
        success: false,
        error: 'Failed to update appointment'
      });
    }
    
    res.json({
      success: true,
      appointment: updatedCheckIn,
      message: 'Next appointment date updated successfully'
    });
  } catch (error: any) {
    res.status(500).json({
      success: false,
      error: 'Failed to update appointment date',
      message: error.message
    });
  }
});

export default router;
