/**
 * @fileoverview Ticket generation routes for Foodbank Check-In and Appointment System backend API
 * 
 * This module handles HTML ticket generation for client check-ins. It generates
 * printable tickets with appointment details, client information, dietary requirements,
 * and pickup instructions for the food bank distribution process.
 * 
 * @author Lindsey D. Stead
 * @version 1.0.0
 * @since 2025-10-20
 * @license Proprietary - see LICENSE file for details
 * 
 * @see {@link ../stores/unifiedStore.ts} Data store for check-in information
 */

import express from 'express';
import { Request, Response } from 'express';
import { getTodayAppointments } from '../stores/unifiedStore';

const router = express.Router();

/**
 * Generate HTML ticket for client check-in
 * 
 * Retrieves check-in data from the unified store and generates a printable
 * HTML ticket with appointment details, client information, and dietary requirements.
 * 
 * @route GET /api/tickets/:checkInId
 * @param {string} checkInId - Unique identifier for the check-in record
 * @returns {string} HTML ticket document
 */
router.get('/:checkInId', async (req: Request, res: Response) => {
  try {
    const { checkInId } = req.params;
    
    // Get check-in data from unified store
    const { getCheckInById } = require('../stores/unifiedStore');
    const checkIn = getCheckInById(checkInId);
    
    if (!checkIn) {
      return res.status(404).json({
        success: false,
        message: 'Check-in not found'
      });
    }

    // Use the check-in record itself as it contains all the client data
    const clientData = checkIn;

    // Get next appointment data from the check-in record (auto-generated)
    const nextAppointment = checkIn.nextAppointmentISO ? {
      pickUpDate: checkIn.nextAppointmentDate,
      pickUpTime: checkIn.nextAppointmentTime,
      pickUpISO: checkIn.nextAppointmentISO,
      ticketNumber: checkIn.ticketNumber,
      isAutoGenerated: checkIn.isAutoGenerated
    } : null;
    
    
    // Get special requests data from check-in record
    const specialRequests = {
      dietaryRestrictions: checkIn.dietaryRestrictions || [],
      allergies: checkIn.allergies || '',
      unwantedFoods: checkIn.unwantedFoods || '',
      additionalInfo: checkIn.additionalInfo || '',
      hasMobilityIssues: checkIn.hasMobilityIssues || false,
      householdInfoChanged: checkIn.householdInfoChanged || false,
      diaperSize: checkIn.diaperSize || ''
    };

    // Generate ticket HTML matching the image design
    const ticketHtml = generateTicketHTML({
      checkIn,
      clientData,
      nextAppointment,
      specialRequests
    });

    res.setHeader('Content-Type', 'text/html');
    res.send(ticketHtml);
  } catch (error: any) {
    console.error('Error generating ticket:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to generate ticket',
      error: error.message
    });
  }
});

/**
 * Generate HTML ticket template
 * 
 * Creates a formatted HTML ticket with client details, appointment information,
 * household details, dietary requirements, and pickup instructions. The ticket
 * is designed for duplex printing with left and right panels.
 * 
 * @param {Object} data - Check-in data including client, appointment, and special requests
 * @returns {string} Complete HTML document for the ticket
 */
function generateTicketHTML(data: {
  checkIn: any;
  clientData: any;
  nextAppointment: any;
  specialRequests: any;
}): string {
  const { checkIn, clientData, nextAppointment, specialRequests } = data;
  
  // Format next appointment as "YYYY-MM-DD @ h:mm AM/PM"
  const formatPickUpDisplay = (iso?: string, date?: string, time?: string) => {
    try {
      if (iso) {
        const d = new Date(iso);
        if (!isNaN(d.getTime())) {
          const yyyy = d.getFullYear();
          const mm = String(d.getMonth() + 1).padStart(2, '0');
          const dd = String(d.getDate()).padStart(2, '0');
          let hours = d.getHours();
          const minutes = String(d.getMinutes()).padStart(2, '0');
          const ampm = hours >= 12 ? 'PM' : 'AM';
          hours = hours % 12;
          if (hours === 0) hours = 12;
          return `${yyyy}-${mm}-${dd} @ ${hours}:${minutes} ${ampm}`;
        }
      }
      if (date && time) return `${date} @ ${time}`;
      if (date) return `${date}`;
    } catch {}
    return 'No next appointment scheduled';
  };

  // Format dietary considerations from check-in record
  const formatDietaryFromFile = () => {
    const csvDietary = clientData.dietaryConsiderations || 'None';
    if (csvDietary === 'None' || !csvDietary) return '';
    return csvDietary.split(',').map((item: string) => item.trim()).join(', ');
  };

  // Format special requests from check-in
  const formatSpecialRequests = () => {
    const requests = [];
    
    if (specialRequests.dietaryRestrictions?.length > 0) {
      requests.push(`Dietary Preferences: ${specialRequests.dietaryRestrictions.join(', ')}`);
    }
    
    if (specialRequests.allergies) {
      requests.push(`Allergies: ${specialRequests.allergies}`);
    }
    
    if (specialRequests.diaperSize) {
      requests.push(`Diaper Size: ${specialRequests.diaperSize}`);
    }
    
    if (specialRequests.hasMobilityIssues) {
      requests.push('Mobility Assistance Required');
    }
    
    if (specialRequests.additionalInfo) {
      requests.push(`Additional Notes: ${specialRequests.additionalInfo}`);
    }
    
    return requests;
  };

  const dietaryFromFile = formatDietaryFromFile();
  const specialRequestsList = formatSpecialRequests();

  return `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lifesaver Technology Services Ticket - ${checkIn.clientName}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            background: white;
        }
        .ticket {
            max-width: 800px;
            margin: 0 auto;
            border: 2px solid #000;
            padding: 20px;
            background: white;
        }
        .ticket-content {
            display: flex;
            gap: 20px;
        }
        .left-panel {
            flex: 1;
            border-right: 2px solid #000;
            padding-right: 20px;
        }
        .right-panel {
            flex: 1;
            padding-left: 20px;
        }
        .header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #000;
            padding-bottom: 10px;
        }
        .sort-button {
            background: #f0f0f0;
            border: 1px solid #000;
            padding: 5px 10px;
            font-size: 12px;
        }
        .logo-section {
            display: flex;
            align-items: center;
            flex-direction: column;
        }
        .logo {
            width: 50px;
            height: 50px;
            margin-bottom: 8px;
            display: flex;
            align-items: center;
            justify-content: center;
        }
        .logo img {
            width: 100%;
            height: 100%;
            object-fit: contain;
        }
        .org-name {
            font-weight: bold;
            font-size: 16px;
            text-align: center;
            line-height: 1.2;
        }
        .order-type {
            background: #f0f0f0;
            border: 1px solid #000;
            padding: 5px 10px;
            font-size: 12px;
        }
        .client-name {
            font-size: 24px;
            font-weight: bold;
            text-align: center;
            margin: 20px 0;
            padding: 15px;
            border: 2px solid #000;
            background: #f0f0f0;
        }
        .appointment-section {
            margin: 20px 0;
            text-align: center;
        }
        .appointment-title {
            font-weight: bold;
            margin-bottom: 10px;
            font-size: 16px;
        }
        .appointment-details {
            font-size: 18px;
            font-weight: bold;
            margin: 10px 0;
        }
        .instructions {
            margin: 20px 0;
            font-size: 14px;
            line-height: 1.4;
            text-align: center;
        }
        .instructions strong {
            font-weight: bold;
        }
        .contact-info-footer {
            text-align: center;
            margin: 20px 0;
            font-size: 14px;
        }
        .contact-info-footer strong {
            font-weight: bold;
        }
        .right-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 20px;
            border-bottom: 1px solid #000;
            padding-bottom: 10px;
        }
        .household-size {
            display: flex;
            align-items: center;
            gap: 10px;
        }
        .household-size select {
            border: 1px solid #000;
            padding: 5px;
        }
        .client-info {
            margin: 10px 0;
            font-size: 16px;
            font-weight: bold;
        }
        .field-group {
            margin: 15px 0;
        }
        .field-label {
            font-weight: bold;
            margin-bottom: 5px;
            font-size: 14px;
        }
        .field-value {
            background: #f9f9f9;
            border: 1px solid #ccc;
            padding: 8px;
            font-size: 14px;
            min-height: 20px;
        }
        .field-row {
            display: flex;
            gap: 10px;
            margin: 10px 0;
        }
        .field-row .field-group {
            flex: 1;
            margin: 0;
        }
        .checkbox-field {
            display: flex;
            align-items: center;
            gap: 5px;
        }
        .checkbox-field input[type="checkbox"] {
            transform: scale(1.2);
        }
        .footer {
            text-align: center;
            margin-top: 20px;
            padding-top: 10px;
            border-top: 1px solid #ccc;
            font-size: 12px;
            color: #666;
        }
        .pickup-instruction {
            font-weight: bold;
            margin-top: 10px;
        }
        @media print {
            body { 
                margin: 0; 
                padding: 10px; 
                -webkit-print-color-adjust: exact;
                color-adjust: exact;
            }
            .ticket { 
                border: 2px solid #000; 
                page-break-inside: avoid;
                width: 100%;
                max-width: none;
            }
            .ticket-content {
                display: flex;
                width: 100%;
            }
            .left-panel, .right-panel {
                flex: 1;
                page-break-inside: avoid;
            }
            /* Force double-sided printing */
            @page {
                size: A4;
                margin: 0.5in;
            }
            /* Ensure content fits on one page */
            .ticket {
                height: 100vh;
                overflow: hidden;
            }
        }
    </style>
</head>
<body>
    <div class="ticket">
        <div class="ticket-content">
            <!-- LEFT PANEL -->
            <div class="left-panel">
                <div class="header">
                    <button class="sort-button">«SortOd»</button>
                    <div class="logo-section">
                        <div class="logo">
                            <img src="/assets/logo1.png" alt="Lifesaver Technology Services Logo" />
                        </div>
                        <div class="org-name">LIFESAVER TECHNOLOGY SERVICES</div>
                    </div>
                    <button class="order-type">«Order_Type_Odd»</button>
                </div>

                <div class="client-name">${checkIn.clientName}</div>

                <div class="appointment-section">
                    <div class="appointment-title">Your next appointment is booked for:</div>
                    <div class="appointment-details">
                        ${formatPickUpDisplay(nextAppointment?.pickUpISO, nextAppointment?.pickUpDate, nextAppointment?.pickUpTime)}
                    </div>
                </div>

                <div class="instructions">
                    <strong>PLEASE ARRIVE AT YOUR ALLOTED TIME SLOT.</strong><br>
                    Due to high volume of appointments,<br>
                    you may be asked to leave and return at your assigned time.
                </div>

                <div class="contact-info-footer">
                    If you need to <strong>reschedule</strong> or are <strong>going to be late,</strong><br>
                    please call 250-763-7161.
                </div>
            </div>

            <!-- RIGHT PANEL -->
            <div class="right-panel">
                <div class="right-header">
                    <button class="sort-button">«SortEy»</button>
                    <div class="household-size">
                        <span>Household Size:</span>
                        <select>
                            <option>${clientData.householdSize || 1}</option>
                        </select>
                    </div>
                </div>

                <div class="client-info">
                    <div>${clientData.lastName || ''}, ${clientData.firstName || ''}</div>
                    <div>Talecia ${checkIn.clientName}</div>
                </div>

                <button class="order-type" style="margin: 10px 0;">«Order_Type_Even»</button>

                <div class="field-row">
                    <div class="field-group">
                        <div class="field-label">Milk:</div>
                        <div class="field-value">${(() => {
                          const householdSize = clientData.householdSize || 1;
                          if (householdSize <= 2) return '1 jug';
                          if (householdSize <= 4) return '2 jugs';
                          if (householdSize <= 6) return '3 jugs';
                          return '4 jugs';
                        })()}</div>
                    </div>
                    <div class="field-group">
                        <div class="field-label">Eggs:</div>
                        <div class="field-value">${(() => {
                          const householdSize = clientData.householdSize || 1;
                          if (householdSize <= 3) return '1 dozen';
                          if (householdSize <= 6) return '2 dozen';
                          return '3 dozen';
                        })()}</div>
                    </div>
                </div>

                <div class="field-group">
                    <div class="field-label">Snack Packs:</div>
                    <div class="checkbox-field">
                        <input type="checkbox" ${specialRequests.dietaryRestrictions?.includes('Snack Packs') ? 'checked' : ''}>
                        <span>Include Snack Packs</span>
                    </div>
                </div>

                <div class="field-group">
                    <div class="field-label">Dietary Requirements:</div>
                    <div class="field-value">${dietaryFromFile || specialRequests.dietaryRestrictions?.join(', ') || 'None'}</div>
                </div>

                <div class="field-row">
                    <div class="field-group">
                        <div class="field-label">Child Ages:</div>
                        <div class="field-value">${clientData.childrensAges || clientData.childrenAges || 'N/A'}</div>
                    </div>
                    <div class="field-group">
                        <div class="field-label">Baby Age:</div>
                        <div class="field-value">${specialRequests.diaperSize || 'N/A'}</div>
                    </div>
                </div>

                <div class="field-group">
                    <div class="field-label">M Ages:</div>
                    <div class="field-value">${clientData.adults || 1} adults, ${clientData.seniors || 0} seniors</div>
                </div>

                <div class="field-group">
                    <div class="field-label">Allergies:</div>
                    <div class="field-value">${specialRequests.allergies || 'None'}</div>
                </div>

                <div class="field-group">
                    <div class="field-label">Unwanted Food:</div>
                    <div class="field-value">${specialRequests.unwantedFoods || 'None'}</div>
                </div>

                <div class="field-group">
                    <div class="field-label">Requests/Notes:</div>
                    <div class="field-value">${specialRequests.additionalInfo || 'None'}</div>
                </div>

                ${specialRequests.hasMobilityIssues ? `
                <div class="field-group">
                    <div class="field-label">Mobility Assistance:</div>
                    <div class="field-value" style="color: #ff6b35; font-weight: bold;">Required</div>
                </div>
                ` : ''}
            </div>
        </div>

        <div class="footer">
            <p>Generated on ${new Date().toLocaleString()}</p>
            <p class="pickup-instruction">Please present this ticket for pickup</p>
        </div>
    </div>
</body>
</html>`;
}

export default router;