export interface CheckInRecord {
  id: string;
  clientId: string;
  clientName: string;
  phoneNumber: string;
  checkInTime: string;
  appointmentTime?: string;
  status: 'Pending' | 'Shipped' | 'Collected' | 'Not Collected' | 'Rescheduled' | 'Cancelled';
  source: 'csv' | 'manual' | 'api';
  
  // Additional fields
  firstName?: string;
  lastName?: string;
  email?: string;
  dietaryConsiderations?: string;
  householdSize?: number;
  adults?: number;
  seniors?: number;
  children?: number;
  childrensAges?: string;
  itemsProvided?: string;
  notes?: string;
  
  // Completion data
  completionTime?: string;
  dietaryRestrictions?: string[];
  allergies?: string;
  unwantedFoods?: string;
  additionalInfo?: string;
  householdInfoChanged?: boolean;
  hasMobilityIssues?: boolean;
  notificationPreference?: string;
  phone?: string;
  phoneCarrier?: string;
  location?: string;
  program?: string; // Link2Feed Program field (e.g., Food Hamper, Emergency Support)
  clientType?: string;
  waitTime?: number;
  
  // Appointment data
  pickUpDate?: string;
  pickUpISO?: string;
  provisions?: string;
  quantity?: number;
  
  // Next appointment data
  nextAppointmentDate?: string;
  nextAppointmentTime?: string;
  nextAppointmentISO?: string;
  ticketNumber?: string;
  isAutoGenerated?: boolean;
  generatedFrom?: string;
  generatedAt?: string;
  
  // Metadata
  createdAt: string;
  updatedAt: string;
  expiresAt: string;
}
